 version: '2'
 services:
    db:
      restart: always
      build: postgres/
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data/
      environment:
        - DEBUG=false
        - DB_USER=postgres
        - DB_PASS=workfree
        - DB_NAME= 'tryton', 'django'

    web:
      restart: always
      build: ./web/
      expose:
        - "8000"
      links:
        - db
        - redis
      env_file: env
      volumes:
        - ./web/:/data/web

      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn present-me.wsgi -b 0.0.0.0:8000"

    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes_from:
        - web
      links:
        - web:web

    redis:
      restart: always
      image: redis:latest
      expose:
        - "6379"
      ports:
        - "6379:6379"

    tryton:
      restart: always
      build: tryton/
      ports:
        - "8050:8000"
      depends_on:
        - db
      links:
        - db


      environment:
        - TRYTOND_DATABASE_URI=postgresql://tryton@db:5432/

 volumes:
  db_data: